version: "3.7"
services:
  nginx:
    container_name: nginx
    image: nginx-certbot
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./src/:/usr/share/nginx/html
      - ./ssl/ssl-params.conf:/etc/nginx/snippets/ssl-params.conf
      - ./ssl/self-signed.conf:/etc/nginx/snippets/self-signed.conf
      - ./ssl/nginx-selfsigned.crt:/ssl/nginx-selfsigned.crt
      - ./ssl/nginx-selfsigned.key:/ssl/nginx-selfsigned.key
      - ./ssl/dhparam.pem:/ssl/dhparam.pem
    ports:
      - 80:80
      - 443:443
    networks:
      - cowsay
    restart: always
  app:
    container_name: app
    image: cowsay
    networks:
      - cowsay
    restart: always
networks:
  cowsay:
    name: cowsay
    driver: bridge
